### ISSUE TITLE
Read, readByQuery & readByName incorrect XML 

### ISSUE THREAD

**Issue by bezoar17** [privateprep/intacct-ruby#15]
### Expected Behavior

The read requests should output a xml like this 
```
<read>
    <object>VENDOR</object>
    <keys>1</keys>
    <fields>*</fields>
</read>
```

### Actual Behavior

The current output is such
```
<read>
    <>
    <object>VENDOR</object>
    <keys>1</keys>
    <fields>*</fields>
    <>
</read>
```

### Steps to reproduce

```
gateway = IntacctRuby::Request.new(request_opts)
gateway.read(nil, {object: "VENDOR", pagesize: 100, fields: '*'})
gateway.to_xml
```

When, the PR #9 was ported to PR #13, a few lines were missed due to which this issue persists.

**Comment by danielpowell4** [comment]
Quick fix shipped in 1.8.3 3/20/18
