### ISSUE TITLE
XML-escape all strings before inserting them into XML

### ISSUE THREAD

**Issue by jzornow** [privateprep/intacct-ruby#2]

**Comment by danielpowell4** [comment]
@jakemaas1

**Comment by danielpowell4** [comment]
I think we can do it here:
https://github.com/privateprep/intacct-ruby/blob/master/lib/intacct_ruby/function.rb#L71

By appending ruby's `.encode(xml: :text)`

Would be good to add a test to be sure breaking chars like &, <, and > go away

**Comment by bezoar17** [comment]
@danielpowell4  https://github.com/privateprep/intacct-ruby/pull/17
