### ISSUE TITLE
Parsing response from request.send?

### ISSUE THREAD

**Issue by bcooper** [privateprep/intacct-ruby#24]
Does someone have a code example of parsing or reading the response object from "request.send" that is a "request.readByQuery" call?  I am struggling to grab the XML query results and parse them.  Any example would help.  Thanks for your help.

**Comment by danielpowell4** [comment]
@bezoar17 any ideas?

**Comment by toddsiegel** [comment]
@bcooper Can you post what code you have so far?

**Comment by bcooper** [comment]
request = IntacctRuby::Request.new(REQUEST_OPTS)

        request.readByQuery nil, {
            object: 'VENDOR',
            query: 'VENDORID = 20952',
            fields: '*',
            pagesize: 100
        }

        response = request.send
-------------
I am getting a successful status returned. But cannot figure out the means to read the "response" returned.  I have only worked with JSON before and not XML so a newbie.  I have tried multiple combinations of parsing this with Nokogiri but it never returns anything.  

Any example of reading a value from the response object would set me straight.  Example:  Grabbing - <result><data><vendor><name>

Apologize this is so elementary of a question.

**Comment by bezoar17** [comment]
Hey, a simple and effective approach is to convert the XML in response to a `Hash` in ruby for easily operating on it. So it would look something like this.

```ruby
request = IntacctRuby::Request.new(REQUEST_OPTS)

request.readByQuery nil, {
    object: 'VENDOR',
    query: 'VENDORID = 20952',
    fields: '*',
    pagesize: 100
}

response = request.send
result_hash = Hash.from_xml(response.response_body.to_s)
```

Now , `result_hash` can be used further in the program.
```ruby
data = res_hash.dig("response", "operation", "result", "data")
vendor_obj = data.dig("vendor")
```

@bcooper , let me know if it helps.

**Comment by bcooper** [comment]
You are a life saver.  I had tried a couple of variations of what you showed but I had not seen the "dig" command plus I was trying to access "response.body.to_s" and not "response.response_body.to_s".  Thank you for taking the time to answer my newbie question.  I will go ahead and close the issue.
