### ISSUE TITLE
Unable to create invoices

### ISSUE THREAD

**Issue by ashishtajane** [privateprep/intacct-ruby#25]
I am trying to create invoices through this gem. There is only legacy API for that as per [this link](https://developer.intacct.com/api/accounts-receivable/invoices/#create-invoice-legacy). Is it currently possible to do that using the gem? Is there any plan to add it if it's not possible right now?
Thanks

**Comment by danielpowell4** [comment]
@ashishtajane Thanks for reaching out. We are only planning to actively support DTD 3 (non-legacy) calls and at the moment. I do not intend to extend backward support to DTD 2- calls.

That being said, you could accomplish this by forking the repo and adding it around here

https://github.com/privateprep/intacct-ruby/blob/master/lib/intacct_ruby/function.rb#L8-L16

 If you have success, I would certainly look at a PR!

Hope this helps

**Comment by ashishtajane** [comment]
Thanks for the prompt reply and the direction.

I was able to get `read` and `create` calls to work by just adding them in the list you mentioned. But for `update` calls, we need to add support for attributes for tags at any level. Like (`key` and `line_num` below):

```xml
<function controlid="{{$guid}}">
  <update_invoice key="123">
    <updateinvoiceitems>
      <updatelineitem line_num="1">
        <memo>hello world</memo>
      </updatelineitem>
    </updateinvoiceitems>
  </update_invoice>
</function>
```

I haven't found any clean and elegant way to do this yet. Will raise a PR if I can get it working.
Thanks for your help. I will close this now then.
