### ISSUE TITLE
Can we add "readEntityDetails" to approved function calls.

### ISSUE THREAD

**Issue by drc37** [privateprep/intacct-ruby#27]
There is some new functionality that list available entities. Any way we can get this added to the list?

readEntityDetails

https://developer.intacct.com/api/company-console/entities/

**Comment by danielpowell4** [comment]
@drc37 thanks for reaching out!

I don't have any current, personal need for it, but I'm certainly happy to look at a PR. 

Should be as easy as adding here:

https://github.com/privateprep/intacct-ruby/blob/master/lib/intacct_ruby/function.rb#L9-L15
https://github.com/privateprep/intacct-ruby/blob/master/README.md

**Comment by drc37** [comment]
Sounds good. I will create one tomorrow.

David Cook
269-370-4760


On May 20, 2019 at 5:23:33 PM, Daniel Powell (notifications@github.com)
wrote:

@drc37 <https://github.com/drc37> thanks for reaching out!

I don't have any current, personal need for it, but I'm certainly happy to
look at a PR.

Should be as easy as adding here:

https://github.com/privateprep/intacct-ruby/blob/master/lib/intacct_ruby/function.rb#L9-L15
https://github.com/privateprep/intacct-ruby/blob/master/README.md

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/privateprep/intacct-ruby/issues/27?email_source=notifications&email_token=AABHV3KLPC53IFAZBIVZNULPWMXHHA5CNFSM4HOGEN52YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODV2KMXY#issuecomment-494184031>,
or mute the thread

**Comment by jakemaas1** [comment]
We are no longer maintaining this project, and we will be archiving the repo. As such we are closing all issues, and will update the readme accordingly.

Apologies for any inconvenience this may cause!
