### ISSUE TITLE
cannot add customfields when creating class

### ISSUE THREAD

**Issue by nomoonx** [privateprep/intacct-ruby#4]

**Comment by danielpowell4** [comment]
@nomoonx Sorry on the extremely slow reply. We recently went through some role changes in terms of gem maintenance

Happy to look into the issue you are having if you could supply a bit more details in terms of what you tried to do and how exactly it failed.

Certainly open to a PR as well!

**Comment by nomoonx** [comment]
No need to say sorry. It's totally fine. 
I've already forked my version and solved my problem in a tricky way. 
Thanks for reply :D

**Comment by danielpowell4** [comment]
Happy to see a PR if you have the time

Have a good rest of the week!
