### ISSUE TITLE
Getting unitialized constant error when trying to use

### ISSUE THREAD

**Issue by asr1901** [privateprep/intacct-ruby#5]
I'm trying to use the basic example to create a sample customer in Intacct.

When I run the job, I see:

$ ruby intacct_test.rb 
/Library/Ruby/Gems/2.0.0/gems/intacct_ruby-1.7.0/lib/intacct_ruby/api.rb:9:in `send_request': uninitialized constant IntacctRuby::Api::Net (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/intacct_ruby-1.7.0/lib/intacct_ruby/request.rb:59:in `send'
	from intacct_test.rb:26:in `<main>'

**Comment by asr1901** [comment]
I am new to Ruby programming but from google, adding the following lines to the top of my script fixed it:

require 'net/http'
require 'uri'

are there any other things I should know to use this gem?

**Comment by danielpowell4** [comment]
@asr1901 Sorry on the infinitely slow reply. We did some internal reshuffling with the gem's maintainers.

Hope you figured the problem out!

It looks like your problem was related to an error raised by the Intacct side of the API rather than anything our side of things. A clear shape of the data you need is available here: https://developer.intacct.com/api/accounts-receivable/customers/#create-customer

In our implementation of the gateway with intacct, we create customers with the following call:

```
# base_gateway.rb

require 'intacct_ruby'

module Accounting
  # Inherited by each specific type of gateway, to cut down on duplicate code.
  # Sends functions and handles any resulting errors.
  class BaseGateway
    include IntacctRuby

    AUTHENTICATION_ATTRIBUTES = {
      companyid:       ENV['INTACCT_COMPANYID'],
      userid:          ENV['INTACCT_USERID'],
      user_password:   ENV['INTACCT_USER_PASSWORD'],
      senderid:        ENV['INTACCT_SENDERID'],
      sender_password: ENV['INTACCT_SENDER_PASSWORD']
    }.freeze

    def send_request(request)
      request.send
    rescue StandardError => error
      raise Accounting::SystemError, "#{error.message}\n\nThis error was triggered by one of the " \
      "following functions:\n\n#{function_descriptions(request.functions)}"
    end

    private

    def function_descriptions(functions)
      functions.each_with_object('') do |function, output|
        output << "#{function.to_xml}\n\n"
      end
    end
  end
end


# client_gateway.rb
module Accounting
  class ClientGateway < BaseGateway

    def initialize(client)
      @client = client # model
    end

    def activate
      request = Request.new(AUTHENTICATION_ATTRIBUTES)
      request.create :CUSTOMER, customer_attrs

      send_request request
    end

    private

    def customer_attrs
      {
        CUSTOMERID: @client.id,
        NAME:       @client.name,
        STATUS:     customer_status,
        CUSTREPID:  @client.managing_director_id,
        DISPLAYCONTACT: {
          PRINTAS:    @client.name,
          FIRST_NAME: @client.first_name,
          LAST_NAME:  @client.last_name,
          EMAIL1:     @client.email
        }
      }
    end

    def customer_status
      'active'
    end
  end
end

```

If you are still on this have any problems, feel free to reopen and reach out!
