### ISSUE TITLE
Read, readByQuery & readByName incorrect DTD

### ISSUE THREAD

**Issue by dior001** [privateprep/intacct-ruby#7]
Hi @jzornow thank you very much for creating this library. 

I'm trying to get started with this code and I might be misinterpreting this but it looks like the XML generated for `read`, `readByQuery` and `readByName` is incorrect. Is this an API version issue?

Example:
```
# REQUEST_OPTS = https://github.com/jzornow/intacct-ruby#authentication-example
request = IntacctRuby::Request.new(REQUEST_OPTS)
request.read :vendor, { keys: 1, fields: '*' }
request.send
```

XML:
```
<?xml version="1.0" encoding="UTF-8"?>
<request>
  <control>
    <senderid>...</senderid>
    <password>...</password>
    <controlid>2017-12-29 01:04:38 UTC</controlid>
    <uniqueid>false</uniqueid>
    <dtdversion>3.0</dtdversion>
    <includewhitespace>false</includewhitespace>
  </control>
  <operation transaction="true">
    <authentication>
      <login>
        <userid>...</userid>
        <companyid>...</companyid>
        <password>...</password>
      </login>
    </authentication>
    <content>
      <function controlid="read-VENDOR-2017-12-29 01:04:38 UTC">
        <read>
          <VENDOR>            
            <KEYS>1</KEYS>
            <FIELDS>*</FIELDS>
          </VENDOR>
        </read>
      </function>
    </content>
  </operation>
</request>
```

Response:
`XML Parse schema error: Error 1871: Element 'VENDOR': This element is not expected...`

It looks like in the docs (https://developer.intacct.com/api/accounts-payable/vendors/#read) the expected XML format is:

```
<read>
    <object>VENDOR</object>
    <keys>1</keys>
    <fields>*</fields>
</read>
```

Apologies in advance if I've misinterpreted the code. I will try and submit a PR that resolves this. Just wanted to make you and anyone else looking at this repo aware this appears to be a problem.

**Comment by danielpowell4** [comment]
Should be fixed in 1.8!
